### ISSUE TITLE
Feature Request: Support original MADH music

### ISSUE THREAD

**Issue by sfiera** [arescentral/antares#110]
Original [issue 107](https://code.google.com/p/antares/issues/detail?id=107) created by ergzay on 2011-12-21T23:09:20.000Z:

The original MADH library that is included with the original source is out of date. The most recent version can be found in the PROPlayer project on sourceforge. 
http://sourceforge.net/projects/playerpro/files/PlayerPRO%20MadLibrary%20%28Driver%29/Dev.Kit%205.9.4/
I think it is possible to bring back the original music playing capability with this rather than using transcoded mp3 files that are lower quality.

**Comment by mlindner** [comment]
Commenting on this in the hopes you see this. I've been trying to find those original MADH files but I can't seem to find them. Do you still have them saved anywhere?

**Comment by sfiera** [comment]
There are no MADH files, per se. In [Ares Data ƒ](https://downloads.arescentral.org/Ares/Ares-1.2.0.zip) there’s a file called Ares Sounds, and the music is in the resource fork. You’ll need PlayerPro to turn them into something usable—though I’m not sure if recent versions of macOS are able to run it in a way that works for this purpose anymore.

**Comment by mlindner** [comment]
> There are no MADH files, per se. In [Ares Data ƒ](https://downloads.arescentral.org/Ares/Ares-1.2.0.zip) there’s a file called Ares Sounds, and the music is in the resource fork. You’ll need PlayerPro to turn them into something usable—though I’m not sure if recent versions of macOS are able to run it in a way that works for this purpose anymore.

The reason why I ask is I think when the original conversion to s3m was done, it was done improperly. Notably the left-right channel distribution of the tracks was removed and also there's what sounds like minor pitch differences between the current files and what it sounded like originally.
