### ISSUE TITLE
Add antares-launcher on Linux

### ISSUE THREAD

**Issue by sfiera** [arescentral/antares#158]
The antares binary supports options for controlling video settings, but they're not suitable for use with a .desktop file. We should add an antares-launcher that serves the same role as the Mac version's pre-game options dialog.

I think a Python/GTK+3 binary is probably good; our needs are pretty minimal. For listing screen sizes, we can use GdkScreen and GdkVisual.

**Comment by sfiera** [comment]
Video settings no longer apply, but plugin settings are needed.

**Comment by Jeryia** [comment]
Tried out the new 0.8.1 release. Thanks for the linux upgrades :)

This is a really stupid question, but... How does one load a plugin with the new linux launcher?

**Comment by sfiera** [comment]
There's nothing in the launcher for it. At the command-line, it should be "antares-install-data foo.antaresplugin". The launcher probably should handle it, but I think first there would need to be a *.desktop file or something?
