### ISSUE TITLE
.gn missing from 0.8.1 source release

### ISSUE THREAD

**Issue by sfiera** [arescentral/antares#182]
It's needed to build Antares, but it's missing from the source release because scripts/dist.py excludes all dotfiles.

**Comment by Mailaender** [comment]
Is it possible to build antares without this `gn`? It doesn't seem to be widely available and I also couldn't find documentation on where to get it for a system wide installation and packaging.

**Comment by sfiera** [comment]
No, not at the moment. In theory, you could generate the .ninja build files centrally and distribute them (you'd have to drop the rule at the top of build.ninja that rebuilds build.ninja) but it wouldn't work with the configure script.

Background: Antares used to use gyp+ninja, which was Chromium's build system. Chromium has since switched away from that to gn+ninja. I can ask the gn developers about packaging—up until recently they were releasing quickly in order to get to the point where it could replace gyp, but now that it has, maybe they can call a release "stable".

**Comment by LeifW** [comment]
FYI, when running `./configure` on Arch Linux, it says gn is missing, and to add some antares .deb repo to install it. That won't work, but `gn` is already available in the Arch system packages: `pacman -S gn` https://archlinux.org/packages/extra/x86_64/gn/
