### ISSUE TITLE
"Oops didn't consume all of scenario file info data"

### ISSUE THREAD

**Issue by OldReliable** [arescentral/antares#187]
Received this error when launching game with plugins: 

The Audemedon Crisis

Its War p2

**Comment by sfiera** [comment]
There was a problem with the Its War plugin. This version should be fixed:
https://sfiera.net/~sfiera/Its-War-2-1.0.6.80.antaresplugin
(I'm not sure if that's where you got it from. If not, it would be helpful to know where, so I can update it there too)

I'll take a look at The Audemedon Crisis this weekend.

**Comment by OldReliable** [comment]
Thanks!

**Comment by sfiera** [comment]
The plugin format has completely changed, so I don’t think this bug would apply anymore. There’s a working version of Audemedon Crisis at https://arescentral.org/plugins, but I haven’t converted over It’s War yet.
