### ISSUE TITLE
Scroll text crashes when no background specified

### ISSUE THREAD

**Issue by TesseractA** [arescentral/antares#200]
Are scenarios supposed to work? I have an issue with running Antares 8.2.0 Footsteps of Phyrrus, it starts up but does not run properly. 

...searched for all terms and files that contained Footsteps of Phyrrus. The folder for Footsteps was inside the antares 8.2.0 file. 

Antares still starts up with the modded image, and the first scenario name when Start New Game is selected. 

The problem comes when the first mission is selected.

I'm probably missing something important there, so I went to diagnose my answer.

When I ran the Antares Unix Executable file inside the Antares file, the launcher started fine and also showed a terminal window I figured any errors would show up there when it quits. 

I selected footsteps in the launcher, then started the game, the special image screen shows up, I click on new game, the first mission pops up as a name, then I select that begin button. Then it quits.
It claims a "segmentation fault" in terminal. 
Isn't segmentation the thing that differentiates between characters/adds images?

I also discovered that Antares does not use ~/Application\ Support/Antares, as the folder does not exist. The default game seems to run fine without it.

Is any of this the fault of the user?

**Comment by sfiera** [comment]
Plugins are supposed to work. I can reproduce your failure, though. I’ll investigate.

**Comment by sfiera** [comment]
Ah, oops. I found it. Will fix it and release 0.8.3, probably today, maybe tomorrow.

**Comment by TesseractA** [comment]
Are Athena files currently compatible with the Antares as well? When I click and drag the scenario (even the default file downloaded from Athena) I'm getting an unexpected crash.

...I also just diagnosed this error by going to Console and reading the Error report. The Antares launcher is asking for a version, and (i'm not sure, but I think so) it is impossible to set a version in the current Athena environment.
_____________
Some critical information:

Application Specific Information:
abort() called
terminating with uncaught exception of type sfz::Exception: /Users/admin/Library/Application Support/Athena/Ares Data/Ares Scenarios: data/version: No such file

Crashed Thread:        6

________
Some less critical information:

Thread 6 Crashed:
0   libsystem_kernel.dylib        	0x00007fff9769ef06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9b0a54ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff97b5f6e7 abort + 129
3   libc++abi.dylib               	0x00007fff96b0af81 abort_message + 257
4   libc++abi.dylib               	0x00007fff96b30a2f default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fff9f5b54a6 _objc_terminate() + 124
6   libc++abi.dylib               	0x00007fff96b2e19e std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff96b2dc12 __cxa_throw + 121
8   org.arescentral.antares       	0x000000010990417c zipxx::ZipFileReader::ZipFileReader(zipxx::ZipArchive&, sfz::StringSlice const&) + 610
9   org.arescentral.antares       	0x000000010988161b antares::(anonymous namespace)::check_version(zipxx::ZipArchive&, sfz::StringSlice) + 66
10  org.arescentral.antares       	0x0000000109881039 antares::DataExtractor::set_plugin_file(sfz::StringSlice) + 123
11  org.arescentral.antares       	0x000000010987498f antares_data_extractor_set_plugin_file + 109
12  org.arescentral.antares       	0x000000010987356a -[AntaresExtractDataController doWork] + 246
13  com.apple.Foundation          	0x00007fff8f1bad64 __NSThread__start__ + 1351
14  libsystem_pthread.dylib       	0x00007fff9b0a299d _pthread_body + 131
15  libsystem_pthread.dylib       	0x00007fff9b0a291a _pthread_start + 168
16  libsystem_pthread.dylib       	0x00007fff9b0a0351 thread_start + 13

Thread 6 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x000070000029eeb8  rdx: 0x0000000000000000
  rdi: 0x0000000000008c0f  rsi: 0x0000000000000006  rbp: 0x000070000029eee0  rsp: 0x000070000029eeb8
   r8: 0x0000000000000004   r9: 0x00007fff96b31a53  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x000070000029f040  r13: 0x000070000029f640  r14: 0x00007000002a0000  r15: 0x000070000029ef20
  rip: 0x00007fff9769ef06  rfl: 0x0000000000000206  cr2: 0x00007f940858c000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     222




Process:               Antares [5047]
Path:                  /Games/*/Antares.app/Contents/MacOS/Antares
Identifier:            org.arescentral.antares
Version:               0.8.2 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Antares [5047]

Date/Time:             2018-02-10 21:15:00.562


Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
