### ISSUE TITLE
Athena-Made Scenario Crashing, possible diagnosis

### ISSUE THREAD

**Issue by TesseractA** [arescentral/antares#201]
NOTE: Copied from another thread.
Are Athena files currently compatible with the Antares as well? When I click and drag the scenario (even the default file downloaded from Athena) I'm getting an unexpected crash.

...I also just diagnosed this error by going to Console and reading the Error report. The Antares launcher is asking for a version, and (i'm not sure, but I think so) it is impossible to set a version in the current Athena environment.
_____________
Some critical information:

Application Specific Information:
abort() called
terminating with uncaught exception of type sfz::Exception: /Users/admin/Library/Application Support/Athena/Ares Data/Ares Scenarios: data/version: No such file

Crashed Thread:        6

________
Some less critical information:

Thread 6 Crashed:
0   libsystem_kernel.dylib        	0x00007fff9769ef06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9b0a54ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff97b5f6e7 abort + 129
3   libc++abi.dylib               	0x00007fff96b0af81 abort_message + 257
4   libc++abi.dylib               	0x00007fff96b30a2f default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fff9f5b54a6 _objc_terminate() + 124
6   libc++abi.dylib               	0x00007fff96b2e19e std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff96b2dc12 __cxa_throw + 121
8   org.arescentral.antares       	0x000000010990417c zipxx::ZipFileReader::ZipFileReader(zipxx::ZipArchive&, sfz::StringSlice const&) + 610
9   org.arescentral.antares       	0x000000010988161b antares::(anonymous namespace)::check_version(zipxx::ZipArchive&, sfz::StringSlice) + 66
10  org.arescentral.antares       	0x0000000109881039 antares::DataExtractor::set_plugin_file(sfz::StringSlice) + 123
11  org.arescentral.antares       	0x000000010987498f antares_data_extractor_set_plugin_file + 109
12  org.arescentral.antares       	0x000000010987356a -[AntaresExtractDataController doWork] + 246
13  com.apple.Foundation          	0x00007fff8f1bad64 __NSThread__start__ + 1351
14  libsystem_pthread.dylib       	0x00007fff9b0a299d _pthread_body + 131
15  libsystem_pthread.dylib       	0x00007fff9b0a291a _pthread_start + 168
16  libsystem_pthread.dylib       	0x00007fff9b0a0351 thread_start + 13

Thread 6 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x000070000029eeb8  rdx: 0x0000000000000000
  rdi: 0x0000000000008c0f  rsi: 0x0000000000000006  rbp: 0x000070000029eee0  rsp: 0x000070000029eeb8
   r8: 0x0000000000000004   r9: 0x00007fff96b31a53  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x000070000029f040  r13: 0x000070000029f640  r14: 0x00007000002a0000  r15: 0x000070000029ef20
  rip: 0x00007fff9769ef06  rfl: 0x0000000000000206  cr2: 0x00007f940858c000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     222

Process:               Antares [5047]
Path:                  /Games/*/Antares.app/Contents/MacOS/Antares
Identifier:            org.arescentral.antares
Version:               0.8.2 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Antares [5047]

Date/Time:             2018-02-10 21:15:00.562

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by sfiera** [comment]
I’m confused. What file are you trying to open with Antares? Antares plugins should have an “.antaresplugin” extension. It looks like you’re trying to open the “Ares Scenarios” file with Antares. That won’t work, and I’m not sure how it’s possible. If I right-click on “Ares Scenarios”, the only application I see in the menu is Athena, and if I drag it to Antares, it doesn’t register as something Antares can open.

If you’re trying to open some other plugin with Antares, then can you link the file here? It will be difficult to diagnose otherwise.

**Comment by TesseractA** [comment]
@sfiera  Athena files aren't compatible with Antares? How would I make a .antaresplugin file? Could I write a python file to convert?

**Comment by sfiera** [comment]
Athena deals with a couple of different file formats. I thought it had Antares support, but when I try to “Save As…”, the only options I get for file format are “Ares Data” (for the original Ares) and “Xsera Scenario”.

I’m not sure what to suggest. If Athena can’t produce an .antaresplugin, then this is an Athena issue, but I’m not familiar enough with Athena to diagnose a problem with it.

**Comment by TesseractA** [comment]
@sfiera How did you generate an ares plugin? Raw coding? If that's so, maybe I can convert the files created in Athena to whatever code has been created in .aresplugin .

**Comment by sfiera** [comment]
I built an updated version of Athena. I’m not sure when the 1.0 was from, but it was too old to have Antares support.
http://downloads.arescentral.org/Athena/Athena-1.1.zip

**Comment by sfiera** [comment]
(going to close this out. If Antares crashes on an .antaresplugin file, feel free to open a new bug)
