### ISSUE TITLE
configure requires a working network connection

### ISSUE THREAD

**Issue by orbea** [arescentral/antares#276]
OS: `Slackware64-current`

When running configure without a working network it will print this warning.
```
checking for python Gtk...
(configure:7242): dbind-WARNING **: 09:20:23.686: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-g2GVkPx7gD: Connection refused
    ok
```
The configure script should never rely on having a working network which users may not have enabled and could be using pre-downloaded sources. It also provides a potential security issue when connecting to unknown servers as root which may or may not be malicious or otherwise compromised.

I am not very familiar with python so I am not really sure where this is coming from, but it can be reproduced easily as root with `unshare(1)`.
```
# unshare -n ./configure
```
And for reference here is the full configure log.
```
# unshare -n ./configure 
checking host os...           linux
checking target os...         linux
checking Linux distro...      Slackware  14.2  (untested)
checking for clang...         ok
checking for libc++...        ok
checking for libc++abi...     ok
checking for python-gi...     ok
checking for python Gtk...
(configure:7242): dbind-WARNING **: 09:20:23.686: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-g2GVkPx7gD: Connection refused
    ok
checking for pkg-config...    ok
checking for gl...            ok
checking for glfw3...         ok
checking for glu...           ok
checking for libmodplug...    ok
checking for libzip...        ok
checking for libpng16...      ok
checking for neon...          ok
checking for openal...        ok
checking for sndfile...       ok
checking for x11...           ok
checking for xcursor...       ok
checking for xinerama...      ok
checking for xrandr...        ok
checking for xxf86vm...       ok
checking for zlib...          ok
configure mode...             opt
generating build.ninja...     ok
make(1) it so!
```

**Comment by orbea** [comment]
Its from this line.
https://github.com/arescentral/antares/blob/07b68068c8b6bb72522de16f64c3e9f6b418b4a9/configure#L258

**Comment by orbea** [comment]
Yea, this page might be helpful, but I am not nearly familiar with python to implement it.

https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

**Comment by orbea** [comment]
@sfiera I found that this issue can be fixed by adding this to my build script before `./configure`.
```
export NO_AT_BRIDGE=1
```
You may wish to add this environment variable to `configure` too?

Reference: https://unix.stackexchange.com/questions/230238/x-applications-warn-couldnt-connect-to-accessibility-bus-on-stderr

**Comment by sfiera** [comment]
I think eventually I decided that the simpler thing was to remove the check from ./configure altogether. It’s a runtime dependency, not a build-time dependency, so there’s not really any need for the check to be there to begin with. I don’t think I actually removed it yet, though.

**Comment by sfiera** [comment]
At HEAD, the launcher is removed entirely, along with these checks.
