### ISSUE TITLE
[Feature request] Defining custom CXXFLAGS

### ISSUE THREAD

**Issue by orbea** [arescentral/antares#277]
Can the python configure script made to override the default optimizations when setting `CXXFLAGS` as an environment variable? It should also not conflict with project specific build flags.

In Slackware this would be used like:
```
CXXFLAGS="$SLKCFLAGS" \
./configure
```
Where on 64-bit systems `$SLKCFLAGS` usually is `-O2 -fPIC`.

**Comment by sfiera** [comment]
Sounds reasonable. I’ll take a look at this when I have some spare time. Is the name CXXFLAGS important? It would match gn better to have three variables CFLAGS_CC, CFLAGS_C, and CFLAGS for flags applied to C++, C, and both.

(I’d also add LDFLAGS for consistency).

**Comment by orbea** [comment]
Thanks!
