### ISSUE TITLE
Unable to load new plugins - Mac OS

### ISSUE THREAD

**Issue by dome2048** [arescentral/antares#332]
I started tinkering around with plugin development, but I couldn't get a single plugin to load. I investigated further, and I can't install any new plugins. I have most of the plugins that are available on arescentral.org, but never did install the _Footsteps of Pyrrhus_ plugin. When I tried to install it (or my custom plugin) by dragging it onto the Antares icon, I get this error:
`Oops
(path to new plugin)/pluginname.antaresplugin: info.pn: No such file`

Every custom plugin I've tried is a zipped folder, with a properly formatted info.pn file in lowest level directory, with the file extension changed to .antaresplugin.

I've scoured the documentation and tried things different ways to see if this might be user error, but at this point I'm out of ideas.

Environment:
Mac OS 10.14.6
Antares 0.9.1

**Comment by sfiera** [comment]
Just to be clear, this is the released 0.9.1, not a nightly, right? In the next release, the plan is to go back to the Ares way (no installation step). I didn’t think there were any relevant changes in 0.9.1, but I’ll take a look.

Here’s are other builds, if you want to try them:
* [Nightly](http://downloads.arescentral.org/Antares/antares-mac-git.zip)
* [0.9.0](http://downloads.arescentral.org/Antares/antares-mac-0.9.0.zip)

**Comment by sfiera** [comment]
I tried it myself and didn’t have any issue installing Footsteps of Pyrrhus 1.2.0 into Antares 0.9.1.

I believe that the error you see comes from [src/data/extractor.cpp:218](https://github.com/arescentral/antares/blob/v0.9.1/src/data/extractor.cpp#L218), and that the zip file must have been successfully opened just prior to that at [src/data/extractor.cpp:395](https://github.com/arescentral/antares/blob/v0.9.1/src/data/extractor.cpp#L395)

When the Oops dialog appears, there is a window behind it saying “Extracting xxxx.antaresplugin…”, right? Can you post a screenshot that shows both the Oops dialog and the window behind? (or copy the text and paste it here)

It might be useful also if you could attach the exact plugin file here, just so I can confirm nothing weird happened to it.

**Comment by dome2048** [comment]
Thanks for the response!

I used the stable build of 0.9.1, but first encountered it on a previous version I had installed (possibly 0.9.0, but I'm not sure). I upgraded to the latest stable to see if it worked.

So, this is strange, but today Footsteps of Pyrrhus did successfully load, though my custom plugin still is not... I might need to keep messing around with my plugin to see if there's something I'm doing wrong, but I do know there's an info.pn file and it's in the same place as the other plugins that are loading properly.

In regards to the windows: when the "Oops" dialog pops up, the Antares menu disappears, and there's nothing behind it when I move the "Oops" dialog out of the way.

I'll try the experimental builds and also keep messing around with the plugin.

**Comment by sfiera** [comment]
Just uploaded a [new build](http://downloads.arescentral.org/Antares/antares-mac-git.zip). With this one, you can drag-and-drop your plugin folder onto the app to try it, instead of needing to zip it up first. (I thought that was already supported, but it wasn’t, so I just fixed it)

If you’re creating a plugin with the Finder’s “Compress” menu item, be careful that you zip the files directly, and not a folder that contains them. If you zip the folder, then your data will be at “/foldername/info.pn” instead of “/info.pn” like Antares expects (though I guess I could fix Antares to handle both). If you do that and can’t get the plugin to load, you can upload it here and I’ll try to debug.

**Comment by dome2048** [comment]
I was definitely compressing the files incorrectly, so I'm sure that was at least part of the problem. 

I tried your new build and when I dragged my folder containing the plugin files to it, Antares crashed. 

I have to work some long days the next few days and won't have a chance to troubleshoot until then, but once I do have some
time I have a few ideas. Also, if it's helpful, I can post the output from the crash reporter.

**Comment by sfiera** [comment]
Sure. Having the plugin itself would also probably be useful for reproducing the crash.

**Comment by dome2048** [comment]
Well, I think this can be closed.

Initially, I encountered this error with my own plugin and with the Footsteps of Pyrrhus, but I haven't been able to reproduce the Footsteps error.

With your help, I realized that I had been zipping the parent folder of the proper files rather than the files themselves.

I also did some more tweaking and realized I had some extraneous files in the plugin I was trying to load. I pared down and only included scenario files (and info.pn), and I was able to get the plugin to load - both as an .antaresplugin file on the release build and as a folder on the build you provided.

I did notice some strange behavior, but I'm not sure it's necessarily a bug. When I make changes to a scenario, I need to change the name of the whole plugin in the info.pn file, otherwise the changes aren't reflected in the gameplay. This might just be part of the development process for plugins.

Thanks for your help in identifying my user errors, and in all your work on this game! It was a gem of my 1990s Power Mac and I'm excited that I will be able to share it with my kids!

**Comment by sfiera** [comment]
> I did notice some strange behavior, but I'm not sure it's necessarily a bug. When I make changes to a scenario, I need to change the name of the whole plugin in the info.pn file, otherwise the changes aren't reflected in the gameplay. This might just be part of the development process for plugins.

Is that with 0.9.1 or the nightly? If it’s 0.9.1, then I guess it’s expected, but if it’s happening with the nightly, I’d want to look into it. When you run a plugin in the nightly, Antares isn’t supposed to be saving that data [anymore].

**Comment by dome2048** [comment]
That was with the nightly. I just tried it a few more times to confirm. I'll open a new issue with more details.
