### ISSUE TITLE
samurai no longer works.

### ISSUE THREAD

**Issue by orbea** [arescentral/antares#353]
OS: `Slackware64-current`
antares: https://github.com/arescentral/antares/commit/c7c02c44c79fe042fdb2d60654d9fd2820d3efa8
samurai: `1.1`

The build system no longer works with samurai after the configure check for ninja was hard coded.
```
checking host os...           linux
checking target os...         linux
checking Linux distro...      Slackware 14.2 x86_64 (post 14.2 -current) (untested)
checking for clang...         ok
checking for gn...            ok
checking for ninja...         missing
checking for pkg-config...    ok
checking for pkg-config...    ok
checking for gl...            ok
checking for glfw3...         ok
checking for glu...           ok
checking for libmodplug...    ok
checking for libpng...        ok
checking for libzip...        ok
checking for neon...          ok
checking for openal...        ok
checking for sndfile...       ok
checking for x11...           ok
checking for xcursor...       ok
checking for xinerama...      ok
checking for xrandr...        ok
checking for xxf86vm...       ok
checking for zlib...          ok

missing dependencies: ninja
On current, you can install it with:

    $ echo deb http://apt.arescentral.org current contrib | sudo tee /etc/apt/sources.list.d/arescentral.list
    $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5A4F5210FF46CEE4B799098BAC879AADD5B51AE9
    $ sudo apt-get update
    $ sudo apt-get install ninja-build

Then, try ./configure again
```
This used to work.
```
./configure --prefix=/usr
make NINJA="samu -C out/cur" install DESTDIR=$PKG
```
The samurai repo can be found here.

https://github.com/michaelforney/samurai

**Comment by orbea** [comment]
Also, why is it checking for pkg-config twice?
```
checking for pkg-config...    ok
checking for pkg-config...    ok
```
I suggest it should look for `pkgconf` first and then look for `pkg-config` if that is not found. Currently the `pkg-config` on my system is a symlink to `pkgconf` and eventually that backwards compatibility might go away.

https://github.com/pkgconf/pkgconf

**Comment by sfiera** [comment]
I think #355 should fix this for you. You should be able to `NINJA=samu ./configure` and `make install DESTDIR=$PKG`.

**Comment by orbea** [comment]
Yes, that works out well. The antares SlackBuild already uses the `NINJA` environment variable to set `samu` instead of the default of `ninja`, this just makes it more convenient. Thanks!

**Comment by sfiera** [comment]
OK, merged. The two points worth noting are:
* NINJA is used by ./configure instead of make now. There’s no need to pass it to make, but no harm.
* You only need NINJA=samu (no -C out/cur), though again I don’t think it does any harm.
