### ISSUE TITLE
./configure depends on submodule

### ISSUE THREAD

**Issue by assertivist** [arescentral/antares#360]
[The Long Instructions](https://arescentral.org/antares/contributing/building), should probably mention the submodules. Currently, when I clone fresh from github, `./configure` fails with `NameError: name 'cfg' is not defined`, but that goes away after the submodules are there.

**Comment by sfiera** [comment]
It’s not supposed to, but I see where I messed up. `./configure` itself is careful to work without the submodule, but I started importing another package that’s not so careful.

**Comment by LeifW** [comment]
I'm still hitting this on a fresh clone. What's the workaround?

**Comment by sfiera** [comment]
Ah, I was catching and ignoring ImportError, but I forgot that ignoring the import error leads to a later NameError.
