### ISSUE TITLE
"Zoom to 1:2" keybind triggers "Zoom to 2:1" instead

### ISSUE THREAD

**Issue by ltdaaannn** [arescentral/antares#382]
As stated in the title, the 1:2 zoom keybind triggers 2:1 zoom instead. I'm playing Antares on a MacBook Pro and without a numpad had to re-bind a lot of the keys; as such I never used the default keybinds. Not sure if that matters at all.

**Comment by sfiera** [comment]
Ah, yeah, I see that in the code. I’ll fix it.
