### ISSUE TITLE
Sounds are not playing correctly on Windows build

### ISSUE THREAD

**Issue by elasota** [arescentral/antares#407]
I'm doing some sanity checks of the XAudio sound driver to make sure everything's functioning correctly.  One thing that seems suspicious is that it seems like it's interrupting sounds quite a bit in busy situations, whereas the original game doesn't seem to interrupt very much - weapon fire for instance usually just gets throttled down to fewer sounds playing at once, but they usually complete, and explosions are almost never interrupted, but in Antares they're interrupted very frequently..

Would it be possible to upload a video capture of the demo from the main menu on Linux or macOS for comparison purposes so I can narrow down whether this is a global problem or a problem with the Windows version specifically?

**Comment by sfiera** [comment]
This is supposed to be the function of [persistence and priority](https://arescentral.org/plugins/format/action#play), so if there’s more interruption than the original, it’s probably a mismatch between the rules described there and the original behavior.

I [recorded a video](https://www.youtube.com/watch?v=4s44qu5zgXE) about 10y ago. It does sound like there’s a lot of interruption, but the explosions sound like they’re mostly playing through. Does it sound different from that to you? I think recent builds sound the same, but I don’t have a capture handy.

**Comment by elasota** [comment]
I'll do a capture of what I'm getting tomorrow, it looks like part of this was due to a lot of sounds playing back at double speed due to resampling not working, causing them to clog up sound slots even though they had already stopped playing.

Some of it looks like it's problems caused by the substituted sounds being quite different from the original game (e.g. the carrier's turret from that demo seems much quieter) but it still seems off, and it's hard to identify differences when the original used different sounds, so it'd be very helpful to get a capture with the OpenAL driver to get a better idea of the expected behavior.

**Comment by sfiera** [comment]
Ah, yeah, I didn’t really try hard to match the replacement sounds, because they’re not generally used in practice. The Mac version downloads and extracts the original sounds on first run, and the Linux version when installing. If you’re asking for a screen capture without them, I’ll see what I can do; I guess I could delete the extracted sounds after the app starts.

**Comment by sfiera** [comment]
Here you go. Yeah, it sounds real bad with the replacement sounds.
https://user-images.githubusercontent.com/166772/158048365-341aa8a8-b4c6-4e5a-b2ba-3f9c9891a220.mov

**Comment by elasota** [comment]
Updated description, I think something is wrong with the XAudio2 backend specifically.  The laser fire at 0:12 in that capture is fairly steady for instance, but in the XAudio2 version it's very choppy.

**Comment by elasota** [comment]
Based on some tests, it seems like what's happening in the XA2 backend is that when a sound is interrupted, it's failing to play the following sound for some reason.  Hitting Warp repeatedly will only play the sound every other time for instance.
