### ISSUE TITLE
Struggling to build on Pop OS 22.04

### ISSUE THREAD

**Issue by macmeister1967** [arescentral/antares#430]
The .configure script is not giving me much helpful information... I am using a Pentium laptop with Intel HD (Mesa) graphics.

It is currently complaining about opengl.pc file or something similar.

Also, cannot get the deb installed from the repository either under Jammy.

any ideas welcomed.

**Comment by sfiera** [comment]
Please post the commands you ran along with the full output.

A .pc file is a pkg-config file, and it's necessary to determine the compilation flag for each library. Possibly, Pop OS installs the library without the specification.

**Comment by macmeister1967** [comment]
I managed to somehow get it installed... under /usr/libexec/antares/antares-glfw

"/home/craig/.local/share/games/antares/scenarios is up-to-date!
antares-glfw: 4cab7415715aeeacf1486a352267ae82c0efb220: scenario not installed"

This is now the issue... I couldn't find the data files under macOS, as they are hidden away somewhere strange?! (I have the original Macintosh ones, but they are named very weirdly, and are all packaged into a single file?)

**Comment by sfiera** [comment]
If you run `make install-data install-scenario` (might need `sudo`) it should download and extract the necessary files from the original game. That should be part of `make install`; did you run it? What was the output?

**Comment by macmeister1967** [comment]
***@***.***:~/Downloads/antares-0.9.1$ ./configure
checking host os...           linux
checking target os...         linux
checking Linux distro...      Pop 22.04 jammy (untested)
checking for clang...         ok
checking for libc++...        ok
checking for libc++abi...     ok
checking for pkg-config...    ok
checking for gl...            ok
checking for glfw3...         ok
checking for glu...           missing
checking for libmodplug...    ok
checking for libzip...        ok
checking for libpng...        ok
checking for neon...          ok
checking for openal...        ok
checking for sndfile...       ok
checking for x11...           ok
checking for xcursor...       ok
checking for xinerama...      ok
checking for xrandr...        ok
checking for xxf86vm...       ok
checking for zlib...          ok

missing dependencies: glu
On Ubuntu, you can install it with:

    $ sudo apt-get install libglu1-mesa-dev

Then, try ./configure again

_________________________________


It is installed, I purged and reinstalled, and it continues to complain...
without configure, I have no make targets :-(

Cheers.

C.

**Comment by sfiera** [comment]
Strange. You’re not getting `glu.pc` when you install `libglu1-mesa-dev`? This is what I see if I test with with a clean Jammy system in Docker:
```sh-session
% docker run --rm -ti ubuntu:jammy
# apt-get update >/dev/null
# apt-get install -y libglu1-mesa-dev pkg-config >/dev/null
# pkg-config --libs glu
-lGLU
# dpkg -L libglu1-mesa-dev |grep glu.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/glu.pc
```

**Comment by macmeister1967** [comment]
Installed FreeGLUT, it now compiles. Antares still brings up the same error, but running antares-glfw runs the game fine

[Oh Yeah!](https://imgur.com/w1fFFTe)

Many thanks for the advice and guidance

**Comment by macmeister1967** [comment]
Before you close this thread, is there any way to play true fullscreen (without menubar) ??

There may even be a linux command to hide the menubar (or I could drag it offscreen).

The macOS version has a starting window allowing you to deselect "windowed".

Just wondering, not a big deal if unavailable.

**Comment by macmeister1967** [comment]
Ummm, still getting that error... I tried reinstalling from .deb package of
0.9.1 converted from Fedora rpm, and it appears to be failing before
downloading and installing scenarios etc.

"N: Download is performed unsandboxed as root as file
'/home/craig/Downloads/antares_0.9.1-2.43_amd64.deb' couldn't be accessed
by user '_apt'. - pkgAcquire::Run (13: Permission denied)"

I am running as SUDO by the way...

Cheers for any advice...

PS. I have the app installed, just nothing much in the
.local/share/game/antares directory. App appears to be working, just
lacking data files.

**Comment by sfiera** [comment]
Again: please post the commands you ran along with the full output.

I don’t know what you’re doing, so it’s impossible for me to tell you what went wrong. Did you ever run `make install` (or `sudo make install`), as I suggested before?

Is building from source actually your goal, or are you just trying to play the game? Did you try the [Ubuntu installation instructions](https://arescentral.org/antares/linux) first?

**Comment by macmeister1967** [comment]
I'm away from the laptop at present, I'll give these commands a shot
tomorrow and report back.

I did a PURGE and reinstall too... weird?!

I am running a lot of other GL games, but they may not be using GLU?

Anyways, I'll let you know tomorrow (I did a locate glu.pc and drew a blank
- this is before the reinstall).

Cheers.

**Comment by macmeister1967** [comment]
I did make it according to the published commands, and it did build and run
correctly, but I need to launch "antares-wfgl" (or whatever it is).

I'm pretty sure this is the correct version, and it runs great. The
binary/shortcut just called "antares" is the one that fails with the same
message(s).
